version: "3"

services:
    app:
        container_name: app
        restart: always
        build: .
        ports: 
            - "3000:3000"
        links:
            - mongo:mongo
        depends_on:
            - mongo
        volumes:
            - uploads:/var/www/api.iturriops.com/dist/uploads
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot   
        environment:
            WAIT_HOSTS: mongo:27017
        networks:
            - app-network
    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - data:/data/db
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot   
        ports: 
            - "27018:27017"
        restart: always
        networks:
            - app-network
    nginx:
        image: nginx:1.15-alpine
        container_name: nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot   
        depends_on:
            - app
        networks:
            - app-network
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    certbot:
        image: certbot/certbot
        container_name: certbot
        restart: always
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot  
        depends_on:
            - nginx
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
volumes:
    data:
    uploads:
    

networks:
    app-network:
        driver: bridge
    