version: "3"

services:
    app:
        container_name: app
        restart: always
        build: .
        ports: 
            - "3000:3000"
        links:
            - mongo:mongo
        depends_on:
            - mongo
        volumes:
            - uploads:/var/www/api.iturriops.com/dist/uploads
            - certbot-webroot-iturriops:/webroots/iturriops.com/.well-known
            - certbot-letsencrypt:/etc/letsencrypt
        environment:
            WAIT_HOSTS: mongo:27017
        networks:
            - app-network
    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - data:/data/db
            - certbot-webroot-iturriops:/webroots/iturriops.com/.well-known
            - certbot-letsencrypt:/etc/letsencrypt
        ports: 
            - "27018:27017"
        restart: always
        networks:
            - app-network
    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - certbot-webroot-iturriops:/webroots/iturriops.com/.well-known
            - certbot-letsencrypt:/etc/letsencrypt
        depends_on:
            - app
        networks:
            - app-network
    certbot:
        build: ./certbot
        container_name: certbot
        volumes:
            - certbot-webroot-iturriops:/webroots/iturriops.com/.well-known
            - certbot-letsencrypt:/etc/letsencrypt
        depends_on:
            - nginx
    
volumes:
    certbot-webroot-iturriops:
    certbot-letsencrypt:
    data:
    uploads:
    

networks:
    app-network:
        driver: bridge
    